module.exports = {
  DURATION_TIME_FORMAT: 'mm:ss.SSS',
  DURATION_TIME_MINUTE_SEPARATOR: ':',
  DURATION_TIME_MS_SEPARATOR: '.',
  MINUTES_MAX_LENGTH: 2,
  SECONDS_MAX_LENGTH: 2,
  MS_MAX_LENGTH: 3
};